package {{escape-kotlin-keyword app.identifier}}

import android.view.Gravity
import android.view.ViewGroup
import android.view.WindowManager

/**
 * F44: Partial-height bottom sheet Activity.
 *
 * Created by `cargo tauri android init` alongside MainActivity.kt.
 * Extends TauriActivity (generated by wry) so `getPluginManager()`
 * and the full Tauri plugin bridge are available.
 *
 * Window layout is applied in onWebViewReady(), which fires after
 * the Activity and WebView are fully wired (IPC, scripts, clients)
 * but before setContentView — avoiding flicker.
 */
open class SheetWryActivity : TauriActivity() {
    override val handleBackNavigation: Boolean = false

    override fun onWebViewReady(webView: RustWebView) {
        val heightFrac = intent.getFloatExtra("height_fraction", 0.6f)
        if (heightFrac < 1.0f) {
            val pxHeight = (resources.displayMetrics.heightPixels * heightFrac).toInt()
            window.setLayout(ViewGroup.LayoutParams.MATCH_PARENT, pxHeight)
            window.setGravity(Gravity.BOTTOM)
            window.addFlags(WindowManager.LayoutParams.FLAG_DIM_BEHIND)
            window.setDimAmount(0.5f)
        }

        // Match WebView background to dashboard theme (#0a0a1a) — no white flicker
        webView.setBackgroundColor(0xFF0a0a1a.toInt())

        super.onWebViewReady(webView)
    }
}
